name: Python Application CI

# Trigger workflow on push to main branch or PR
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Lint Python code (optional)
    - name: Lint code with flake8
      run: |
        pip install flake8
        flake8 .

    # Step 5: Run tests (optional)
    # Add your test command if you have any unit tests
    - name: Run tests
      run: |
        echo "No tests defined yet"

    # Step 6: Run Streamlit app (for test only, optional)
    # Note: GitHub Actions cannot host Streamlit UI; this is just to ensure app runs without errors
    - name: Test Streamlit app
      run: |
        streamlit run personalized_study_planner.py --headless & sleep 10
