name: Personalized Exam Study Planner CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Change if your project uses a different version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint Python code
      run: |
        pip install flake8
        flake8 .

    - name: Run tests
      run: |
        pip install pytest
        pytest || echo "No tests found, skipping"

    - name: Check Streamlit scripts
      run: |
        python -m py_compile app.py  # Replace app.py with your main Streamlit file
